### ISSUE TITLE
Pull Requests

### ISSUE THREAD

**Issue by ankitrajan** [karlogonzales/software-process-agile-341#8]
I am having a bit of difficulty with the pull requests. Do I have to create a new branch every time I want to upload or modify a file? Should I just directly upload it to the master instead? Because right now, I have a couple of files I added on my branch but I don't know how to send them up to the master!

**Comment by karlogonzales** [comment]
Currently, your branch is behind the master branch. You should update your branch before you edit that way when you try to merge into the master there will be no conflicts. If you just want to change something in the README file. You might as well do it directly to the master in browser.
